default:
    base: http://localhost
    base_url: http://localhost/projects/drivermaps
    base_dir: /projects/drivermaps
    db_type: mysql
    db_host: localhost
    db_name: drivermaps
    db_username: root
    db_password: "localhost"
    db_namespace: DriverMaps
    routing: default
    lang: en

    media_directory: media